recipient = input('Enter the recipient: ')
message = input('Enter the message: ')
name = input('Enter the name: ')
subject = input('Enter the subject: ')
version = input('Enter the version: ')
discount = float(input('Enter the discount: '))
status = input('Enter the status: ')
code = input('Enter the code: ')
location = input('Enter the location: ')
age = input('Enter the age: ')
companyName = input('Enter the company name: ')
website = input('Enter the website: ')
phone = input('Enter the phone: ')
jobTitle = input('Enter the job title: ')
department = input('Enter the department: ')

discountRounded = f"{discount:.2f}"
print('Dear %s, I hope this email finds you well.' % (recipient))
print(message)
print('Subject:', subject,"\nSender:",name,'\nVersion:',version)
print(''.join(['Discount: ',str(discountRounded),"%"]))
print('Status:',status,'\nCode:',code,'\nLocation:',location,'\nAge:',age,'\nCompany:',companyName,'\nWebsite:',website,'\nPhone:',phone,'\nJob Title:',jobTitle,'\nDepartment:',department)